# Generated by Django 5.1.1 on 2025-01-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0002_alter_userimages_options_alter_useruploads_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertexts',
            options={'verbose_name': 'User Text', 'verbose_name_plural': 'User Texts'},
        ),
    ]
