# Generated by Django 5.1.1 on 2025-03-09 18:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0004_usermedia_delete_userimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userUploads',
            new_name='users',
        ),
    ]
