# Generated by Django 5.1.1 on 2025-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0005_rename_useruploads_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uniLink',
            field=models.URLField(default='https://yourdomain.com/default/', max_length=100),
            preserve_default=False,
        ),
    ]
