# Generated by Django 5.1.1 on 2025-04-21 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0006_users_unilink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['user'], name='Entry_users_user_id_e0c564_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['uploaded_at'], name='Entry_users_uploade_166546_idx'),
        ),
    ]
