# Generated by Django 5.1.1 on 2025-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0007_users_entry_users_user_id_e0c564_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='guest_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='uniLink',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['profile'], name='Entry_userm_profile_ca3f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['file'], name='Entry_userm_file_25bced_idx'),
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['uploaded_at'], name='Entry_userm_uploade_5b06cd_idx'),
        ),
        migrations.AddIndex(
            model_name='usertexts',
            index=models.Index(fields=['profile'], name='Entry_usert_profile_81e949_idx'),
        ),
        migrations.AddIndex(
            model_name='usertexts',
            index=models.Index(fields=['message'], name='Entry_usert_message_554d43_idx'),
        ),
        migrations.AddIndex(
            model_name='usertexts',
            index=models.Index(fields=['uploaded_at'], name='Entry_usert_uploade_92c5f3_idx'),
        ),
    ]
