# Generated by Django 5.1.1 on 2025-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0008_users_guest_expires_at_users_is_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='storage',
            field=models.IntegerField(default=25),
        ),
    ]
