# Generated by Django 5.1.1 on 2025-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0009_users_is_premium_users_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
