# Generated by Django 5.1.1 on 2025-08-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0010_usermedia_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='storage',
            field=models.FloatField(default=25600),
        ),
    ]
