# Generated by Django 5.2.5 on 2025-09-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0011_alter_users_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
