# Generated by Django 5.2.5 on 2025-10-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0012_users_premium_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, default=False, max_length=254),
        ),
    ]
