# Generated by Django 5.2.5 on 2025-10-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0013_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
