# Generated by Django 5.2.5 on 2025-10-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0014_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
