# Generated by Django 5.2.5 on 2025-10-10 19:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0015_users_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='profile',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='Entry_profi_user_id_b0d69d_idx',
            old_name='Entry_users_user_id_e0c564_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='Entry_profi_uploade_253a9f_idx',
            old_name='Entry_users_uploade_166546_idx',
        ),
    ]
