# Generated by Django 5.2.5 on 2025-10-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0016_rename_users_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ending_premium',
            field=models.BooleanField(default=False),
        ),
    ]
