# Generated by Django 5.1.1 on 2025-01-16 19:36

import Entry.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimages',
            options={'verbose_name': 'User Upload', 'verbose_name_plural': 'User Uploads'},
        ),
        migrations.AlterModelOptions(
            name='useruploads',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Entry.models.userFiles),
        ),
        migrations.CreateModel(
            name='userTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Entry.useruploads')),
            ],
        ),
    ]
