# Generated by Django 5.1.1 on 2025-02-23 18:58

import Entry.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entry', '0003_alter_usertexts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='userMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=Entry.models.userFiles)),
                ('content_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Entry.useruploads')),
            ],
            options={
                'verbose_name': 'User Files',
                'verbose_name_plural': 'User Files',
            },
        ),
        migrations.DeleteModel(
            name='userImages',
        ),
    ]
